# This script follows up on the previous one (EPE_feature_association_buffer_difference_1.py) by taking the yearly fractions of EPEs 
# associated with each feature and performing pixel-wise Wilcoxon tests to determine where the differences between the model and ERA5 are statistically significant. 
# It then plots the difference maps with hatching to indicate non-significant areas.

import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import os
from scipy import stats
from matplotlib.colors import BoundaryNorm

# Helper: build rectangle vertices (for plotting domain boundaries)
def build_rectangle_vertices(rlon, rlat):
    rlon = np.asarray(rlon)
    rlat = np.asarray(rlat)
    if rlon.ndim == 1 and rlat.ndim == 1:
        rlon, rlat = np.meshgrid(rlon, rlat)
    top    = np.column_stack([rlon[-1, :], rlat[-1, :]])
    bottom = np.column_stack([rlon[ 0, :], rlat[ 0, :]])
    left   = np.column_stack([rlon[:, 0],  rlat[:, 0]])
    right  = np.column_stack([rlon[:, -1], rlat[:, -1]])
    return np.vstack([bottom, right, top[::-1], left[::-1]])

# --- CONFIG ---
model_name = "RACMO2" # HCLIM or MetUM or RACMO2
percentile = 999
features = ['AR', 'CY', 'ACY', 'FR', 'JET', 'OTHER']
feature_titles = ["(a) ARs", "(b) CYs", "(c) ACYs", "(d) FRs", "(e) JETs", "(f) OTHER"]
P_THRESHOLD = 0.05
DiffFolder = os.path.abspath(f'EPE_Significance_Maps_{model_name}_vs_ERA5_{percentile}')
os.makedirs(DiffFolder, exist_ok=True)

# 1. Load Grid Info
domain_file = xr.open_dataset('PolarRES_WP3_Antarctic_domain_expanded.nc')
inner_domain_file = xr.open_dataset('PolarRES_WP3_Antarctic_domain.nc')

rlon, rlat = domain_file['rlon'].values, domain_file['rlat'].values
rlon_inner, rlat_inner = inner_domain_file['rlon'].values, inner_domain_file['rlat'].values
rlon2D, rlat2D = np.meshgrid(rlon, rlat)

# Build vertices for the yellow (outer) and black (inner) boxes
verts_outer = build_rectangle_vertices(rlon, rlat)
verts_inner = build_rectangle_vertices(rlon_inner, rlat_inner)

rotated_pole = domain_file['rotated_pole'].attrs
rotated_crs = ccrs.RotatedPole(pole_longitude=rotated_pole['grid_north_pole_longitude'], 
                               pole_latitude=rotated_pole['grid_north_pole_latitude'])

inner_domain_file.close()
domain_file.close()

# 2. Load Yearly Data (generated by EPE_feature_association_buffer_difference_1.py)
print("📂 Loading yearly results...")
h_data = np.load(f'{DiffFolder}/EPE_Yearly_Results_{model_name}_{percentile}.npz')
e_data = np.load(f'{DiffFolder}/EPE_Yearly_Results_ERA5_{percentile}.npz')

def run_stats_and_plot(mode='absolute'):
    fig, axs = plt.subplots(2, 3, figsize=(30, 16), subplot_kw={'projection': ccrs.Orthographic(0, -90)})
    axs = axs.flatten()
    
    cmap = plt.cm.RdBu_r
    if mode == 'absolute':
        levels = np.array([-25, -20, -15, -10, -5, -2.5, 2.5, 5, 10, 15, 20, 25]) # arbitrary but focused on the expected range of differences in percentage points
    else:
        levels = np.array([-100, -80, -60, -40, -20, -10, 10, 20, 40, 60, 80, 100])

    norm = BoundaryNorm(levels, ncolors=cmap.N, extend='both')

    for i, feat in enumerate(features):
        print(f"   ... Analyzing {feat}")
        ax = axs[i]
        
        h_years = h_data[feat]
        e_years = e_data[feat]
        
        # 1. Pixel-wise Wilcoxon significance
        p_map = np.ones(h_years.shape[1:])
        ny, nx = h_years.shape[1:]
        
        for y in range(ny):
            for x in range(nx):
                s1 = h_years[:, y, x]
                s2 = e_years[:, y, x]
                diff = s1 - s2
                # Clean zero differences for Wilcoxon safety
                d_test = diff[diff != 0]
                
                if len(d_test) >= 8: # Matching the len >= 8 safety from your snippet
                    try:
                        _, p = stats.wilcoxon(d_test, mode='approx')
                        p_map[y, x] = p
                    except Exception as e:
                        print(f"Error at pixel ({y}, {x}): {e}")
                        p_map[y, x] = 1.0

        # 2. Calculate means
        h_mean = np.nanmean(h_years, axis=0)
        e_mean = np.nanmean(e_years, axis=0)
        
        if mode == 'absolute':
            diff_map = h_mean - e_mean
        else:
            diff_map = np.divide(h_mean - e_mean, e_mean, 
                                 out=np.zeros_like(e_mean), where=e_mean > 1.0) * 100

        # --- PLOTTING SECTION ---
        ax.set_extent([-180, 180, -90, -20], crs=ccrs.PlateCarree()) 
        ax.coastlines(resolution='50m', linewidth=0.8) 
        
        # Plot the domain boxes
        ax.plot(verts_outer[:,0], verts_outer[:,1], color="#EABB0F", linewidth=2, transform=rotated_crs)
        ax.plot(verts_inner[:,0], verts_inner[:,1], color="k", linewidth=1.5, transform=rotated_crs)
        
        mesh = ax.pcolormesh(
            rlon2D, rlat2D, diff_map,
            transform=rotated_crs,
            cmap=cmap,
            norm=norm,
            shading='auto'
        )
        
        # Hatching for non-significance
        insig_mask = p_map > P_THRESHOLD
        ax.contourf(rlon2D, rlat2D, insig_mask, levels=[0.5, 1.5], transform=rotated_crs,
                    hatches=['////'], colors='none', alpha=0)
        
        ax.set_title(f"{feature_titles[i]}", fontsize=20, fontweight='bold')

    # Colorbar styling
    cbar = fig.colorbar(mesh, ax=axs, orientation='horizontal', extend='both', 
                        fraction=0.05, pad=0.05, aspect=20)
    
    label_text = 'Difference in Fraction of EPEs associated with Features (% points)' if mode == 'absolute' else 'Relative Difference (%)'
    cbar.set_label(label_text, fontsize=20)
    cbar.ax.tick_params(labelsize=14)

    # Save logic
    save_path = f"{DiffFolder}/{mode.capitalize()}_Diff_Significance_{percentile}.png"
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close(fig)


run_stats_and_plot(mode='absolute') # we mostly care about absolute differences in percentage points, but relative differences can be insightful too (if needed)
# run_stats_and_plot(mode='relative')

print(f"\n🎉 Done! Results saved in {DiffFolder}")